<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationIcon>83b7c3318014316d7442ea970ea97d2c0fdd3b5e_full.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="83b7c3318014316d7442ea970ea97d2c0fdd3b5e_full.ico" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="CommonLibrary">
      <HintPath>..\CommonLibrary\bin\Debug\net10.0\CommonLibrary.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="RLocalizationManager.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>RLocalizationManager.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="RLocalizationManager.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
      <LastGenOutput>RLocalizationManager.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
